apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch-local
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch-local
