apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  labels:
    app: zipkin_simple
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      # cause we want to access on the host the service (for convenience: http://$(minikube ip):30411)
      nodePort: 30411
  selector:
    app: zipkin_simple
