# To connect from a container:
# $ apk add postgresql-client
# $ psql -U postgres -h $POSTGRES_SERVICE_HOST -p $POSTGRES_SERVICE_PORT postgres
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-local
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-local
