apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus_simple
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      # cause we want to access on the host the service (for convenience: http://$(minikube ip):9090)
      nodePort: 9090
  selector:
    app: prometheus_simple
